### PR TITLE
Enable short hexadecimal color notation

### PR DESCRIPTION
**Pull request by lucasmichot**
Enable short hexadecimal color notation

### CODE REVIEW

**Comment by blaugueux** [comment]
@lucasmichot do you plan to finish this PR?

**Comment by lucasmichot** [comment]
I have to dig again into it, when I'll have time - let me some days

**Comment by lucasmichot** [comment]
FInished @blaugueux

**Comment by blaugueux** [comment]
Can you squash your commits please

**Comment by lucasmichot** [comment]
Done

**Pull request merged**
