### PR TITLE
Add more StyleCI fixers

### PR DESCRIPTION
**Pull request by lucasmichot**
Add more StyleCI fixers

---

Note: https://styleci.io/analyses/XNAPxp can be auto-applied

### CODE REVIEW

**Comment by blaugueux** [comment]
Maybe we should we use the "symfony" preset. It's a standard now.

**Comment by lucasmichot** [comment]
Done @blaugueux

**Comment by blaugueux** [comment]
That's better

@lucasmichot do you plan a PR fixing all CS ?

**Comment by lucasmichot** [comment]
Hmm - not clear to me
If you merge this PR, and have enabled the autofixing feature in StyleCI, a PR will be created with all the fixes

**Comment by blaugueux** [comment]
I'm not a huge fan of this kind of automation :/

**Comment by blaugueux** [comment]
I'll test it.

**Pull request merged**
