### PR TITLE
Factorize convertHashToArrayOfBoolean

### PR DESCRIPTION
**Pull request by lucasmichot**
Factorize convertHashToArrayOfBoolean

---

https://styleci.io/analyses/87aKnZ can be automerged

### CODE REVIEW

**Comment by blaugueux** [comment]
Please try to fix your CS. It will be more clean to avoid StyleCI commit.

**Comment by blaugueux** [comment]
Thanks for all your work here :)

**Comment by lucasmichot** [comment]
Done

**Comment by blaugueux** [comment]
Nice thanks :+1:

**Pull request merged**
