### PR TITLE
Switch to PSR-4 and remove autoload

### PR DESCRIPTION
**Pull request by lucasmichot**
Unless I don't see the real use of `src/Identicon/autoload.php`?

### CODE REVIEW

**Comment by blaugueux** [comment]
Can you please squash your commits. Thx

**Comment by blaugueux** [comment]
Can you please rebase this PR and squash your commits.

**Comment by lucasmichot** [comment]
Rebased and squashed @blaugueux

**Comment by blaugueux** [comment]
Good job 👍

**Pull request merged**
